name: Awake Action
on:
  schedule:
    - cron: "45 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # awake a secret uri
      - name: secret-awake
        uses: devpolo/awake-action@v1
        with:
          url: ${{ secrets.HEROKU_URI }}
